<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tsubera
 * Date: 12.06.13
 * Time: 13:34
 * To change this template use File | Settings | File Templates.
 */

namespace TwentyFifth\Migrations\Manager;


/** @noinspection PhpUndefinedClassInspection */
class SchemaManagerTest extends \PHPUnit_Framework_TestCase {
	private $sql;

	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->sql = <<<SQL
SELECT pg_catalog.setval('customers_cus_id_seq', 3, true);

SELECT * from COPY
WHERE
	stdin = 2;

SELECT * FROM COPY WHERE stdin = 2;

--
-- TOC entry 1931 (class 0 OID 30000)
-- Dependencies: 162 1938
-- Data for Name: plugins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY plugins (plu_id, plu_name, plu_active, plu_timer_type, plu_timer_default, plu_function) FROM stdin;
8	SimpleQuery::Activity	t	interval	10	create_customer_database_activity
7	SimpleQuery::DatabaseSize	t	run_at	0 0 * * *	create_customer_database_size
9	SimpleQuery::IndexStat	t	run_at	0 0 * * *	create_customer_database_stat_indexes
11	SimpleQuery::TableStat	t	run_at	0 0 * * *	create_customer_database_stat_tables
12	SimpleQuery::TableSize	t	run_at	0 0 * * *	create_customer_database_table_size
10	SimpleQuery::IndexSize	t	run_at	0 0 * * *	create_customer_database_index_size
13	SimpleQuery::IndexStatio	f	run_at	0 0 * * *	create_customer_database_statio_indexes
14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables
\.

SELECT * from bar;

SQL;

	}

	public function testHasCopyFromStdinFalse()
	{
		$this->assertFalse(SchemaManager::hasCopyFromStdin(""));
	}

	public function testHasCopyFromStdinTrue()
	{
		$this->assertTrue(SchemaManager::hasCopyFromStdin($this->sql));
	}

	public function testHasCopyFromStdinBogus()
	{
		$this->assertFalse(SchemaManager::hasCopyFromStdin("SELECT * from copy_foo;"));
	}

	public function testExtractCommandsFromSql()
	{
		$sql = <<<SQL
SELECT * FROM foo;
SELECT * FROM COPY WHERE stdin = 2;

--
-- TOC entry 1931 (class 0 OID 30000)
-- Dependencies: 162 1938
-- Data for Name: plugins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY plugins (plu_id, plu_name, plu_active, plu_timer_type, plu_timer_default, plu_function) FROM stdin;
14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables
14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables
14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables
\.

SELECT * from bar;
SQL;

		$expected = array(
			array('pg_query',
"SELECT * FROM foo;
SELECT * FROM COPY WHERE stdin = 2;

--
-- TOC entry 1931 (class 0 OID 30000)
-- Dependencies: 162 1938
-- Data for Name: plugins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY plugins (plu_id, plu_name, plu_active, plu_timer_type, plu_timer_default, plu_function) FROM stdin;"),
			array('pg_put_line', "14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables"),
			array('pg_put_line', "14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables"),
			array('pg_put_line', "14	SimpleQuery::TableStatio	f	run_at	0 0 * * *	create_customer_database_statio_tables"),
			array('pg_end_copy', ""),
			array('pg_query', "
SELECT * from bar;"),
		);

		$this->assertEquals($expected, SchemaManager::extractCommandsFromSql($sql));
	}
}